dist: xenial
language: ruby
cache: bundler
sudo: false

addons:
  postgresql: "10"
  apt:
    sources:
      - travis-ci/sqlite3
    packages:
      - sqlite3

services:
  - mysql
  - postgresql

before_install: gem install bundler -v '~> 1.17'

matrix:
  include:
    - rvm: 3.0.2
      gemfile: gemfiles/activerecord_master.gemfile
      env: "DB=sqlite"
    - rvm: 3.0.2
      gemfile: gemfiles/activerecord_master.gemfile
      env: "DB=postgresql"
    - rvm: 3.0.2
      gemfile: gemfiles/activerecord_master.gemfile
      env: "DB=mysql"
    - rvm: 2.7.4
      gemfile: gemfiles/activerecord_6_1.gemfile
      env: "DB=sqlite"
    - rvm: 2.7.4
      gemfile: gemfiles/activerecord_6_1.gemfile
      env: "DB=postgresql"
    - rvm: 2.7.4
      gemfile: gemfiles/activerecord_6_1.gemfile
      env: "DB=mysql"
    - rvm: 2.7.4
      gemfile: gemfiles/activerecord_6_0.gemfile
      env: "DB=sqlite"
    - rvm: 2.7.4
      gemfile: gemfiles/activerecord_6_0.gemfile
      env: "DB=postgresql"
    - rvm: 2.7.4
      gemfile: gemfiles/activerecord_6_0.gemfile
      env: "DB=mysql"
    - rvm: 2.6.8
      gemfile: gemfiles/activerecord_5_2.gemfile
      env: "DB=sqlite"
    - rvm: 2.6.8
      gemfile: gemfiles/activerecord_5_2.gemfile
      env: "DB=postgresql"
    - rvm: 2.6.8
      gemfile: gemfiles/activerecord_5_2.gemfile
      env: "DB=mysql"
    - rvm: 2.5.9
      gemfile: gemfiles/activerecord_5_1.gemfile
      env: "DB=sqlite"
    - rvm: 2.5.9
      gemfile: gemfiles/activerecord_5_1.gemfile
      env: "DB=postgresql"
    - rvm: 2.5.9
      gemfile: gemfiles/activerecord_5_1.gemfile
      env: "DB=mysql"
    - rvm: 2.4.10
      gemfile: gemfiles/activerecord_5_0.gemfile
      env: "DB=sqlite"
    - rvm: 2.4.10
      gemfile: gemfiles/activerecord_5_0.gemfile
      env: "DB=postgresql"
    - rvm: 2.4.10
      gemfile: gemfiles/activerecord_5_0.gemfile
      env: "DB=mysql"
    - rvm: 2.3.8
      gemfile: gemfiles/activerecord_4_2.gemfile
      env: "DB=postgresql"
    - rvm: 2.3.8
      gemfile: gemfiles/activerecord_4_2.gemfile
      env: "DB=sqlite"
    # Please note that gem can't be tested against MySQL on ActiveRecord 4.2 (Dump and restore test doesn't work)!
